#!/usr/bin/env python3

import sys
import json
import twitter
from datetime import datetime as dt
from os import environ as env


def today():
    return dt.strftime(dt.now(), "%Y-%m-%d")


def get_timeline(api=None, pinned_status=0):
    return list(filter(lambda x: pinned_status > 0 and x.id != pinned_status,
                       map(lambda y: y, api.GetUserTimeline(count=300))))


def backup_tweets(timeline=[]):
    date = today()
    with open(f"timeline-{date}.json", 'w+') as j:
        for status in timeline:
            j.write(json.dumps(status._json))
            j.write('\n')


def remove_tweets(timeline=[]):
    for status in timeline:
        api.DestroyStatus(int(status.id))
        print (f"-> Removed {status.id}")


if __name__ == "__main__":
    if not ("CONSUMER_KEY" in env and
            "CONSUMER_SECRET" in env and
            "ACCESS_TOKEN_KEY" in env and
            "ACCESS_TOKEN_SECRET" in env):
        sys.stderr.write("Twitter API credentials not set.")
        sys.exit(1)
    else:
        api = twitter.Api(
            env.get('CONSUMER_KEY'),
            env.get('CONSUMER_SECRET'),
            env.get('ACCESS_TOKEN_KEY'),
            env.get('ACCESS_TOKEN_SECRET')
        )
        pinned_status = env.get("PINNED_STATUS", 0)
        timeline = get_timeline(api, int(pinned_status))
        backup_tweets(timeline)
        remove_tweets(timeline)
